### PR TITLE
Add parameter for custom_iam_policy_name

### LINKED ISSUE #24: IAM Policy name EC2PolicyToEnableSSM blocks other region provisioning
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you are interested in working on this issue or have submitted a pull request, please leave a comment!***

***

### Summary
The module can't be executed in other region ( e.g in `ap-southeast-3` ) if it's already executed before ( e.g in `ap-southeast-1` ), especially the IAM Policy because it's a global resource.

Terraform fails when executing `terraform apply`
 

### Module Version

```v0.4.3```

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.13.x
+ provider.aws v3.70.0
```

### Affected Resource(s)

* module.session_manager_config.aws_iam_policy.this

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.
module "session_manager_config" {
  source         = "traveloka/session-manager-config/aws"
  version        = "0.4.3"
  environment    = local.environment
  product_domain = local.product_domain
}
```

### Expected Behavior

- Provisioned the policy properly

### Actual Behavior

- Create the policy with the same name.

### Screnshots

```
  # module.session_manager_config.aws_iam_policy.this will be created
  + resource "aws_iam_policy" "this" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "EC2PolicyToEnableSSM"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "ssm:UpdateInstanceInformation",
                          + "ssm:UpdateInstanceAssociationStatus",
                          + "ssm:UpdateAssociationStatus",
                          + "ssm:PutInventory",
                          + "ssm:PutConfigurePackageResult",
                          + "ssm:PutComplianceItems",
                          + "ssm:ListInstanceAssociations",
                          + "ssm:ListAssociations",
                          + "ssm:GetParameters",
                          + "ssm:GetManifest",
                          + "ssm:GetDocument",
                          + "ssm:GetDeployablePatchSnapshotForInstance",
                          + "ssm:DescribeDocument",
                          + "ssm:DescribeAssociation",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowSSMActions"
                    },
                  + {
                      + Action   = [
                          + "ec2messages:SendReply",
                          + "ec2messages:GetMessages",
                          + "ec2messages:GetEndpoint",
                          + "ec2messages:FailMessage",
                          + "ec2messages:DeleteMessage",
                          + "ec2messages:AcknowledgeMessage",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowEC2Messages"
                    },
                  + {
                      + Action   = [
                          + "ssmmessages:OpenDataChannel",
                          + "ssmmessages:OpenControlChannel",
                          + "ssmmessages:CreateDataChannel",
                          + "ssmmessages:CreateControlChannel",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowSSMMessages"
                    },
                  + {
                      + Action   = "cloudwatch:PutMetricData"
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowCloudWatchPutMetrics"
                    },
                  + {
                      + Action   = "ec2:DescribeInstanceStatus"
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowEC2DescribeInstanceStatus"
                    },
                  + {
                      + Action   = [
                          + "s3:PutObject",
                          + "s3:ListMultipartUploadParts",
                          + "s3:ListBucketMultipartUploads",
                          + "s3:ListBucket",
                          + "s3:GetEncryptionConfiguration",
                          + "s3:GetBucketLocation",
                          + "s3:AbortMultipartUpload",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::default-ssm-logs-ap-southeast-3-480175286602/*",
                          + "arn:aws:s3:::default-ssm-logs-ap-southeast-3-480175286602",
                        ]
                      + Sid      = "AllowS3Logging"
                    },
                  + {
                      + Action   = [
                          + "logs:PutLogEvents",
                          + "logs:CreateLogStream",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:logs:ap-southeast-3:480175286602:log-group:/aws/ssm/session-manager:log-stream:*",
                          + "arn:aws:logs:ap-southeast-3:480175286602:log-group:/aws/ssm/session-manager",
                        ]
                      + Sid      = "AllowCWLLogging"
                    },
                  + {
                      + Action   = [
                          + "logs:DescribeLogStreams",
                          + "logs:DescribeLogGroups",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowCWLReadAccess"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
      + tags_all  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ iam_policy_arn = "arn:aws:iam::480175286602:policy/EC2PolicyToEnableSSM" -> (known after apply)
```

### Steps to Reproduce

1. `terraform apply`
2. `<any_command_you_executed>`

### References

* #0000

### PR DESCRIPTION
**Pull request by dimazyuwono**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #24 

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-session-manager-config/blob/master/CHANGELOG.md):

```release-note
NOTES:

* This will enable you to define a custom iam policy name ( e.g `EC2PolicyToEnableSSM-[random_id]` or `EC2PolicyToEnableSSM-ap-southeast-3` )

```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan
  # module.session_manager_config.aws_iam_policy.this will be created
  + resource "aws_iam_policy" "this" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "EC2PolicyToEnableSSM-ap-southeast-3"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "ssm:UpdateInstanceInformation",
                          + "ssm:UpdateInstanceAssociationStatus",
                          + "ssm:UpdateAssociationStatus",
                          + "ssm:PutInventory",
                          + "ssm:PutConfigurePackageResult",
                          + "ssm:PutComplianceItems",
                          + "ssm:ListInstanceAssociations",
                          + "ssm:ListAssociations",
                          + "ssm:GetParameters",
                          + "ssm:GetManifest",
                          + "ssm:GetDocument",
                          + "ssm:GetDeployablePatchSnapshotForInstance",
                          + "ssm:DescribeDocument",
                          + "ssm:DescribeAssociation",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowSSMActions"
                    },
                  + {
                      + Action   = [
                          + "ec2messages:SendReply",
                          + "ec2messages:GetMessages",
                          + "ec2messages:GetEndpoint",
                          + "ec2messages:FailMessage",
                          + "ec2messages:DeleteMessage",
                          + "ec2messages:AcknowledgeMessage",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowEC2Messages"
                    },
                  + {
                      + Action   = [
                          + "ssmmessages:OpenDataChannel",
                          + "ssmmessages:OpenControlChannel",
                          + "ssmmessages:CreateDataChannel",
                          + "ssmmessages:CreateControlChannel",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowSSMMessages"
                    },
                  + {
                      + Action   = "cloudwatch:PutMetricData"
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowCloudWatchPutMetrics"
                    },
                  + {
                      + Action   = "ec2:DescribeInstanceStatus"
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowEC2DescribeInstanceStatus"
                    },
                  + {
                      + Action   = [
                          + "s3:PutObject",
                          + "s3:ListMultipartUploadParts",
                          + "s3:ListBucketMultipartUploads",
                          + "s3:ListBucket",
                          + "s3:GetEncryptionConfiguration",
                          + "s3:GetBucketLocation",
                          + "s3:AbortMultipartUpload",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::default-ssm-logs-ap-southeast-3-480175286602/*",
                          + "arn:aws:s3:::default-ssm-logs-ap-southeast-3-480175286602",
                        ]
                      + Sid      = "AllowS3Logging"
                    },
                  + {
                      + Action   = [
                          + "logs:PutLogEvents",
                          + "logs:CreateLogStream",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:logs:ap-southeast-3:480175286602:log-group:/aws/ssm/session-manager:log-stream:*",
                          + "arn:aws:logs:ap-southeast-3:480175286602:log-group:/aws/ssm/session-manager",
                        ]
                      + Sid      = "AllowCWLLogging"
                    },
                  + {
                      + Action   = [
                          + "logs:DescribeLogStreams",
                          + "logs:DescribeLogGroups",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = "AllowCWLReadAccess"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
      + tags_all  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

### CODE REVIEW

**Review by radengoots — APPROVED** [review]

**Comment by dimazyuwono** [comment]
hi @radengoots , need your help to review this PR again 🙏

**Comment by radengoots** [comment]
> hi @radengoots , need your help to review this PR again pray

Create a ticket here https://29022131.atlassian.net/servicedesk/customer/portal/11, I don't have admin permission.

**Review by aashari — APPROVED** [review]
LGTM

**Comment by jordhy97** [comment]
Hi @aashari / @radengoots, could you help to merge this PR and release a new version?

**Comment by emilylomempow** [comment]
Hi @aashari, @radengoots, any update on this? 

> Hi @aashari / @radengoots, could you help to merge this PR and release a new version?

**Pull request merged**
